apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  {{ $oauth2Proxy := index .Values "oauth2-proxy" }}
  name: {{ $oauth2Proxy.config.existingSecret }}
spec:
  backendType: systemManager
  data:
  - name: client-id
    key: {{ .Values.secretReference }}
    property: {{ .Values.clientIdSecretProperty }}
  - name: client-secret
    key: {{ .Values.secretReference }}
    property: {{ .Values.clientSecretSecretProperty }}
  - name: cookie-secret
    key: {{ .Values.secretReference }}
    property: {{ .Values.cookieSecretSecretProperty }}
