apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuerName }}
spec:
  acme:
    server: {{ .Values.letsencryptServer }}
    email: {{ .Values.letsencryptEmail }}
    privateKeySecretRef:
      name: {{ .Values.clusterIssuerName }}
    solvers:
    - dns01:
        digitalocean:
          tokenSecretRef:
            name: schooner-cert-manager-dns-credentials
            key: access-token
