apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: schooner-cert-manager-dns-credentials
spec:
  backendType: systemManager
  data:
  - name: access-token
    key: {{ .Values.digitaloceanAccessTokenReference }}
    property: {{ .Values.digitaloceanAccessTokenProperty }}
