apiVersion: v2
description: NGINX ingress controller
name: schooner-ingress-controller
version: 1.0.0
dependencies:
  - name: ingress-nginx
    version: 4.0.13
    repository: https://kubernetes.github.io/ingress-nginx
