apiVersion: v2
description: Deploys applications to the cluster
name: schooner-argo-cd
version: 1.0.0
dependencies:
  - name: argo-cd
    version: 3.29.4
    repository: https://argoproj.github.io/argo-helm
