{
 "title": "Application Performance",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Application",
    "query": "label_values(nodejs_version_info, job)"
   },
   {
    "name": "Pod",
    "query": "label_values(nodejs_version_info, instance)"
   },
   {
    "name": "Path",
    "query": "label_values(http_request_duration_milliseconds, path)"
   }
  ]
 },
 "panels": [
  { "title": "Application Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average Response Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(http_request_duration_milliseconds{job=~'$Application',instance=~'$Pod',path=~'$Path',quantile=\"0.5\"})"
    }
   ]
  },
  {
   "title": "Reqests Per Minute",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_milliseconds_count{job=~'$Application',instance=~'$Pod',path=~'$Path'}[1m]))"
    }
   ]
  },
  {
   "title": "HTTP 4XX Per Minute",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(http_request_buckets_milliseconds_bucket{le=\"+Inf\",code=~\"4(.*)\",job=~'$Application',instance=~'$Pod',path=~'$Path'}[1m]))"
    }
   ]
  },
  {
   "title": "HTTP 5XX Per Minute",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(http_request_buckets_milliseconds_bucket{le=\"+Inf\",code=~\"5(.*)\",job=~'$Application',instance=~'$Pod',path=~'$Path'}[1m]))"
    }
   ]
  },
  {
   "title": "Requests Per Min by Path",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_milliseconds_count{job=~'$Application',instance=~'$Pod',path=~'$Path'}[1m])) by (path, method)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Requests Per Min by Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "none", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_milliseconds_count{job=~'$Application',instance=~'$Pod',path=~'$Path'}[1m])) by (status)",
     "legendFormat": "HTTP {{status}}"
    }
   ]
  },
  {
   "title": "Request Duration Instant by Path",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_milliseconds_sum{job=~'$Application',instance=~'$Pod',path=~'$Path'}[1m])) by (path, method) / sum(increase(http_request_duration_milliseconds_count{job=~'$Application',instance=~'$Pod',path=~'$Path'}[1m])) by (path, method)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Request Duration Instant by Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_milliseconds_sum{job=~'$Application',instance=~'$Pod',path=~'$Path'}[1m])) by (status) / sum(increase(http_request_duration_milliseconds_count{job=~'$Application',instance=~'$Pod',path=~'$Path'}[1m])) by (status)",
     "legendFormat": "HTTP {{status}}"
    }
   ]
  },
  {
   "title": "Request Duration Quantile by Path",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(http_request_duration_milliseconds{job=~'$Application',instance=~'$Pod',path=~'$Path',quantile=\"0.5\"}) by (path, method)",
     "legendFormat": "{{method}} {{path}} - p50"
    },
    {
     "expr": "avg(http_request_duration_milliseconds{job=~'$Application',instance=~'$Pod',path=~'$Path',quantile=\"0.99\"}) by (path, method)",
     "legendFormat": "{{method}} {{path}} - p99"
    }
   ]
  },
  {
   "title": "Request Duration Quantile by Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(http_request_duration_milliseconds{job=~'$Application',instance=~'$Pod',path=~'$Path',quantile=\"0.5\"}) by (status)",
     "legendFormat": "HTTP {{status}} - p50"
    },
    {
     "expr": "max(http_request_duration_milliseconds{job=~'$Application',instance=~'$Pod',path=~'$Path',quantile=\"0.99\"}) by (status)",
     "legendFormat": "HTTP {{status}} - p99"
    }
   ]
  },
  { "title": "NodeJS Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Active Handles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(nodejs_active_handles_total{job=~'$Application',instance=~'$Pod'}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(nodejs_active_requests_total{job=~'$Application',instance=~'$Pod'}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(nodejs_eventloop_lag_seconds{job=~'$Application',instance=~'$Pod'}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Heap Space Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(nodejs_heap_size_used_bytes{job=~'$Application',instance=~'$Pod'}) by (instance) / sum(nodejs_heap_size_total_bytes{job=~'$Application',instance=~'$Pod'}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}