name: Template Cluster

on:
  push:
    branches:
      - main

jobs:
  template:
    name: Template
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
      - name: Template cluster
        uses: tim-ings/schooner/actions/template-cluster@HEAD
        with:
          awsAccessKeyId: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          awsSecretAccessKey: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          digitalOceanToken: "${{ secrets.DO_TOKEN }}"
          digitalOceanClusterName: "${{ secrets.DO_CLUSTER_NAME }}"
          digitalOceanClusterContext: "${{ secrets.DO_CLUSTER_CONTEXT }}"
