name: Apply Cluster

on:
  push:
    branches:
      - main

jobs:
  apply:
    name: Apply Cluster
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
      - name: Apply cluster
        uses: tim-ings/schooner/actions/apply-cluster@HEAD
        with:
          awsAccessKeyId: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          awsSecretAccessKey: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          digitalOceanToken: "${{ secrets.DO_TOKEN }}"
          digitalOceanClusterName: tim-test
          digitalOceanClusterContext: do-sgp1-tim-test
